CREATE TABLE conversion_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_amount NUMERIC(19, 6) NOT NULL,
    source_currency VARCHAR(3) NOT NULL,
    target_currency VARCHAR(3) NOT NULL,
    rate NUMERIC(19, 8) NOT NULL,
    converted_amount NUMERIC(19, 6) NOT NULL,
    quote_date DATE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    owner_id VARCHAR(36) NOT NULL
);

CREATE INDEX idx_conversion_history_owner_created
    ON conversion_history (owner_id, created_at DESC, id DESC);

CREATE INDEX idx_conversion_history_created
    ON conversion_history (created_at);
